jobs:
  jreleaser:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
        token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup env
      uses: ./.github/actions/setup-tests
    - continue-on-error: true
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD
          }}
        JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME: ${{ secrets.JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME
          }}
      name: Do release
      run: nix develop .#jReleaser --command ${{ inputs.release-script-to-run }}
    - continue-on-error: true
      if: always()
      name: JReleaser release output
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      with:
        name: jreleaser-release
        path: 'out/jreleaser/trace.log

          out/jreleaser/output.properties

          '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___jreleaser.yml
