env:
  JAVA_DISTRIBUTION: temurin
jobs:
  sbom:
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    environment: SBOM-store
    name: Generate and store SBOM
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: 17
    - continue-on-error: true
      id: get-date
      name: Get date for cache
      run: echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      name: Use Maven dependency cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: Build project
      run: 'mvn -B test-compile

        '
    - continue-on-error: true
      name: Generate provenance
      uses: slsa-framework/github-actions-demo@9474e92bbf825d5b4b46810fc9367dfc73429a2a
      with:
        artifact_path: .
        output_path: provenance.json
    - continue-on-error: true
      name: Add deployment SSH private key to agent
      run: 'ssh-agent -a ${{ env.SSH_AUTH_SOCK }} > /dev/null

        ssh-add - <<< "${{ secrets.SBOM_DEPLOY_SSH }}"

        echo ${{ env.SSH_AUTH_SOCK }}

        '
    - continue-on-error: true
      env:
        GIT_EMAIL: spoon+sbom@kth.se
        GIT_USER: provenance-bot
        REMOTE_REPO_URL: git@github.com:chains-project/sbom-files.git
      name: Push provenance to remote
      run: 'git config --global user.name "${{ env.GIT_USER }}"

        git config --global user.email "${{ env.GIT_EMAIL }}"

        git clone $REMOTE_REPO_URL

        mkdir -p sbom-files/spoon/slsa

        cp provenance.json sbom-files/spoon/slsa/$(date +%s)-${{ github.sha }}.sbom.json

        cd sbom-files

        git add .

        git commit -m "Spoon: ${{ github.sha }}"

        git push

        '
name: sbom
on:
  repository_dispatch:
    types: trigger-ga___sbom.yml
