env:
  MAVEN_OPTS: -Dmaven.resolver.transport=native -Daether.connector.connectTimeout=300000
    -Daether.connector.requestTimeout=300000
  NIX_OPTIONS: --ignore-environment --keep MAVEN_OPTS --keep PATH --keep LANG
jobs:
  codegen:
    name: Codegeneration
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup env
      uses: ./.github/actions/setup-tests
    - continue-on-error: true
      name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} --command true
    - continue-on-error: true
      name: Run codegen checks
      run: nix develop ${{ env.NIX_OPTIONS }}  --command codegen
  coverage:
    name: Test with coverage
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup env
      uses: ./.github/actions/setup-tests
    - continue-on-error: true
      name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} --command true
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
      name: Run tests with coverage
      run: nix develop ${{ env.NIX_OPTIONS }} --keep PR_NUMBER --keep GITHUB_TOKEN
        --command coverage
  extra:
    name: Extra checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup env
      uses: ./.github/actions/setup-tests
    - continue-on-error: true
      name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command true
    - continue-on-error: true
      name: Run extra checks
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command extra
    - continue-on-error: true
      if: github.repository == 'INRIA/spoon' && github.event_name == 'pull_request'
      name: Trigger extra remote tasks
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command extra-remote
  javadoc:
    name: Javadoc quality
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup env
      uses: ./.github/actions/setup-tests
    - continue-on-error: true
      name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command true
    - continue-on-error: true
      name: Build spoon
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command mvn -f spoon-pom
        -B install -Dmaven.test.skip=true -DskipDepClean
    - continue-on-error: true
      name: Run Javadoc quality check
      run: nix develop ${{ env.NIX_OPTIONS }} .#extraChecks --command javadoc-quality
  maven-central-requirements:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup env
      uses: ./.github/actions/setup-tests
    - continue-on-error: true
      name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} --command true
    - continue-on-error: true
      name: Check maven pom quality
      run: nix develop ${{ env.NIX_OPTIONS }} --command maven-pom-quality
  reproducible-builds:
    name: reproducible-builds
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup env
      uses: ./.github/actions/setup-tests
    - continue-on-error: true
      name: Time nix setup
      run: nix develop ${{ env.NIX_OPTIONS }} --command true
    - continue-on-error: true
      name: Check status
      run: nix develop ${{ env.NIX_OPTIONS }} --command reproducible-builds
  test-linux:
    name: Tests with Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup env
      uses: ./.github/actions/setup-tests
    - continue-on-error: true
      name: Time nix setup
      run: nix develop .#jdk${{ matrix.java }} ${{ env.NIX_OPTIONS }} --command true
    - continue-on-error: true
      name: Test
      run: nix develop .#jdk${{ matrix.java }} ${{ env.NIX_OPTIONS }} --command test
    strategy:
      matrix:
        java:
        - 17
        - 21
        os:
        - ubuntu-latest
  test-windows:
    name: Tests with Java 17 on windows-latest
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Disable Git's autocrlf
      run: git config --global core.autocrlf false
    - continue-on-error: true
      name: git checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Test
      run: 'cp chore/logback.xml src/test/resources/

        mvn -f spoon-pom test

        cat testResults.spoon

        '
name: tests
on:
  repository_dispatch:
    types: trigger-ga___tests.yml
